app = 'flag-day-reminder-bot'
primary_region = 'waw'

[env]
NODE_ENV = "production"
NOTIFICATION_TIME = "7"
STORAGE_PATH = "/data"
TIMEZONE = "Europe/Riga"

[mounts]
source = "bot_data"
destination = "/data"

[http_service]
auto_start_machines = true
auto_stop_machines = false
force_https = true
internal_port = 8080
min_machines_running = 1
max_machines_count = 1
processes = [ "app" ]

[checks.health]
port = 8080
type = "http"
interval = "30s"
timeout = "5s"
grace_period = "10s"
method = "GET"
path = "/health"
protocol = "http"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024