app = 'flag-day-reminder-bot'
primary_region = 'waw'

[env]
NODE_ENV = "production"
PORT = "3000"
STORAGE_PATH = "/data"
TIMEZONE = "Europe/Riga"
NOTIFICATION_TIME = "7"

[mounts]
source = "bot_data"
destination = "/data"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_000
min_machines_running = 0
max_machines_count = 1
processes = [ "app" ]

[checks.health]
port = 3000
type = "http"
interval = "300s"
timeout = "10s"
grace_period = "30s"
method = "GET"
path = "/health"
protocol = "http"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024