app = 'flag-day-reminder-bot'
primary_region = 'arn'

[build]

[env]
NODE_ENV = "production"
PORT = "3000"
STORAGE_PATH = "/data"
TIMEZONE = "Europe/Riga"

[mounts]
source = "bot_data"
destination = "/data"

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 1

[checks.health]
port = 3000
type = "http"
interval = "60s"
timeout = "5s"
grace_period = "10s"
method = "GET"
path = "/health"
protocol = "http"

[[vm]]
memory = '1gb'
cpu_kind = 'shared'
cpus = 1
memory_mb = 1024